/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package stkdatvanphongapp;
import java.awt.FlowLayout;

import javax.swing.BorderFactory;
import javax.swing.JPanel;
import java.awt.Color;

/**
 *
 * @author capta
 */
public class BaiDaDang extends javax.swing.JPanel {

    /**
     * Creates new form BaiDaDang
     */
    public BaiDaDang() {
        initComponents();
        addPostCards(); // Gọi hàm load bài đăng khi khởi tạo
    }

    private void addPostCards(){
        try {
            java.sql.Connection con = OracleConnection.getConnection();
            String sql = "SELECT p.title, p.post_id FROM POSTS p WHERE p.user_id = ? ORDER BY p.post_id DESC";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, CurrentUser.id);
            java.sql.ResultSet rs = pst.executeQuery();
            PanelThemBD.removeAll();
            PanelThemBD.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
            while (rs.next()) {
                String title = rs.getString("title");
                int postId = rs.getInt("post_id");
                BaiDangCard card = new BaiDangCard();
                card.setPostId(postId); 
                card.setTitle(title); // Hàm setTitle cần có trong BaiDangCard
                PanelThemBD.add(card);
            }
            rs.close();
            pst.close();
            con.close();
            PanelThemBD.revalidate();
            PanelThemBD.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelThemBD = new javax.swing.JPanel();
        ThemButton = new javax.swing.JButton();

        javax.swing.GroupLayout PanelThemBDLayout = new javax.swing.GroupLayout(PanelThemBD);
        PanelThemBD.setLayout(PanelThemBDLayout);
        PanelThemBDLayout.setHorizontalGroup(
            PanelThemBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        PanelThemBDLayout.setVerticalGroup(
            PanelThemBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelThemBD);

        ThemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.jpg"))); // NOI18N
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThemButton)
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        // TODO add your handling code here:
        new ThemPhong().setVisible(true);
    }//GEN-LAST:event_ThemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelThemBD;
    private javax.swing.JButton ThemButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
