/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package stkdatvanphongapp;
import javax.swing.BorderFactory;
import java.awt.Color;
import javax.swing.BoxLayout;

/**
 *
 * @author capta
 */
public class BaiDangCard extends javax.swing.JPanel {
    private int postId;
    /**
     * Creates new form BaiDangCard
     */
    public BaiDangCard() {
        initComponents();
        Title.setEditable(false);
        Title.setOpaque(true); // Nếu muốn giống JLabel
        Title.setFocusable(false); // Không cho focus
        Title.setBackground(new Color(255,255,255)); // Đặt nền trắng
    }
    public void setTitle(String m)
    {
        Title.setText(m);
    }
    public void setPostId(int postId) {
        this.postId = postId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Title = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50), 2));
        setPreferredSize(new java.awt.Dimension(150, 100));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        Title.setColumns(20);
        Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Title.setLineWrap(true);
        Title.setRows(5);
        Title.setWrapStyleWord(true);
        Title.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Title.setRequestFocusEnabled(false);
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Title);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) { // Chuột trái
            SuaXoaBD suaXoaBD = new SuaXoaBD();
            suaXoaBD.setLocationRelativeTo(null); // Hiển thị ở giữa màn hình
            suaXoaBD.setVisible(true);
        }
    }//GEN-LAST:event_TitleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Title;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
