/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stkdatvanphongapp;

/**
 *
 * @author capta
 */
public class SuaXoaBD extends javax.swing.JFrame {
    private SuaBaiDang suaBaiDangPanel;
    private SuaPhong suaPhongPanel;

    /**
     * Creates new form SuaXoaBD
     */
    public SuaXoaBD() {
        initComponents();
         // Thiết lập CardLayout cho PanelSuaXoa nếu chưa có
    PanelSuaXoa.setLayout(new java.awt.CardLayout());

    // Tạo panel SuaBaiDang mới (giả sử bạn đã có class SuaBaiDang)
    suaBaiDangPanel = new SuaBaiDang();

    // Thêm panel vào PanelSuaXoa với tên "cardSuaBaiDang"
    PanelSuaXoa.add(suaBaiDangPanel, "cardSuaBaiDang");

    // Hiển thị panel vừa thêm
    java.awt.CardLayout cl = (java.awt.CardLayout) PanelSuaXoa.getLayout();
    cl.show(PanelSuaXoa, "cardSuaBaiDang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuaXoa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LuuButton = new javax.swing.JButton();
        XoaButton = new javax.swing.JButton();
        Backward = new javax.swing.JLabel();
        Forward = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelSuaXoa.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelSuaXoaLayout = new javax.swing.GroupLayout(PanelSuaXoa);
        PanelSuaXoa.setLayout(PanelSuaXoaLayout);
        PanelSuaXoaLayout.setHorizontalGroup(
            PanelSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        PanelSuaXoaLayout.setVerticalGroup(
            PanelSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LuuButton.setBackground(new java.awt.Color(51, 51, 51));
        LuuButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LuuButton.setForeground(new java.awt.Color(255, 255, 255));
        LuuButton.setText("Lưu");
        LuuButton.setBorder(null);
        LuuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuButtonActionPerformed(evt);
            }
        });

        XoaButton.setBackground(new java.awt.Color(51, 51, 51));
        XoaButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        XoaButton.setForeground(new java.awt.Color(255, 255, 255));
        XoaButton.setText("Xóa");
        XoaButton.setBorder(null);
        XoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaButtonActionPerformed(evt);
            }
        });

        Backward.setBackground(new java.awt.Color(255, 255, 255));
        Backward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muiten1.png"))); // NOI18N
        Backward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackwardMouseClicked(evt);
            }
        });

        Forward.setBackground(new java.awt.Color(255, 255, 255));
        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muiten2.png"))); // NOI18N
        Forward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForwardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Backward)
                .addGap(64, 64, 64)
                .addComponent(Forward)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(LuuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(XoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Forward)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LuuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(XoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(Backward))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelSuaXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 392, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PanelSuaXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 101, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LuuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuButtonActionPerformed

    }//GEN-LAST:event_LuuButtonActionPerformed

    private void XoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XoaButtonActionPerformed

    private void ForwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForwardMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) PanelSuaXoa.getLayout();
    // Nếu chưa có panel SuaPhong thì tạo và add vào CardLayout
    if (suaPhongPanel == null) {
        suaPhongPanel = new SuaPhong();
        PanelSuaXoa.add(suaPhongPanel, "cardSuaPhong");
    }
    // Nếu đang ở card SuaBaiDang thì chuyển sang SuaPhong
    cl.show(PanelSuaXoa, "cardSuaPhong");

    }//GEN-LAST:event_ForwardMouseClicked

    private void BackwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackwardMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) PanelSuaXoa.getLayout();
    // Kiểm tra panel hiện tại
    java.awt.Component current = null;
    for (java.awt.Component comp : PanelSuaXoa.getComponents()) {
        if (comp.isVisible()) {
            current = comp;
            break;
        }
    }
    if (current == suaBaiDangPanel) {
        // Nếu đang ở card SuaBaiDang thì thoát và đóng cửa sổ
        this.dispose();
    } else {
        // Nếu không, chuyển về card SuaBaiDang
        cl.show(PanelSuaXoa, "cardSuaBaiDang");
    }
    }//GEN-LAST:event_BackwardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaXoaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaXoaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaXoaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaXoaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaXoaBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backward;
    private javax.swing.JLabel Forward;
    private javax.swing.JButton LuuButton;
    private javax.swing.JPanel PanelSuaXoa;
    private javax.swing.JButton XoaButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
