CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone_number VARCHAR2(15),
    role VARCHAR2(20) CHECK (role IN ('Quản lý', 'Admin', 'Người cho thuê', 'Người thuê')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE ROOM_TYPES (
    room_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(50) UNIQUE NOT NULL,
    description VARCHAR2(200)
);



CREATE TABLE LOCATIONS (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR2(100) UNIQUE NOT NULL,
    address VARCHAR2(200) NOT NULL
);


CREATE TABLE ROOMS (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name VARCHAR2(100) NOT NULL,
    room_type_id NUMBER REFERENCES ROOM_TYPES(room_type_id) ON DELETE CASCADE,
    location_id NUMBER REFERENCES LOCATIONS(location_id) ON DELETE CASCADE,
    area NUMBER NOT NULL,
    price_per_night NUMBER NOT NULL,
    capacity NUMBER NOT NULL,
    description VARCHAR2(500)
);



CREATE TABLE PACKAGES (
    package_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_name VARCHAR2(100) NOT NULL,
    price NUMBER NOT NULL,
    duration_days NUMBER NOT NULL
);



CREATE TABLE POSTS (
    post_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    room_id NUMBER REFERENCES ROOMS(room_id) ON DELETE CASCADE,
    package_id NUMBER REFERENCES PACKAGES(package_id) ON DELETE CASCADE,
    title VARCHAR2(150) NOT NULL,
    content VARCHAR2(2000) NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BOOKINGS (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    room_id NUMBER REFERENCES ROOMS(room_id) ON DELETE CASCADE,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    total_price NUMBER NOT NULL,
    guest_count NUMBER NOT NULL,
    booking_status VARCHAR2(20) DEFAULT 'pending' CHECK (booking_status IN ('pending', 'confirmed', 'cancelled')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE REVIEWS (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    room_id NUMBER REFERENCES ROOMS(room_id) ON DELETE CASCADE,
    rating NUMBER CHECK (rating BETWEEN 1 AND 5) NOT NULL,
    review_comment VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SEARCH_HISTORY (
    search_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    search_content VARCHAR2(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
------------------



INSERT INTO ROOMS (room_name, room_type_id, location_id, area, price_per_night, capacity, description) VALUES
('Phòng đơn 101', 1, 1, 15, 500000, 1, 'Phòng đơn tại trung tâm Hà Nội'),
('Phòng đôi 201', 2, 2, 25, 1000000, 2, 'Phòng đôi rộng rãi tại Đà Nẵng'),
('Phòng gia đình 301', 3, 3, 40, 2000000, 4, 'Phòng gia đình tại TP.HCM');

INSERT INTO ROOM_TYPES (type_name, description) VALUES
('Phòng đơn', 'Phòng nhỏ dành cho 1 người'),
('Phòng đôi', 'Phòng dành cho 2 người'),
('Phòng gia đình', 'Phòng rộng cho cả gia đình'),
('Phòng suite', 'Phòng cao cấp, tiện nghi');

INSERT INTO LOCATIONS (location_name, address) VALUES
('Hà Nội', 'Số 1, Phố Tràng Tiền, Hoàn Kiếm, Hà Nội'),
('Đà Nẵng', 'Số 2, Đường Bạch Đằng, Hải Châu, Đà Nẵng'),
('Hồ Chí Minh', 'Số 3, Đường Nguyễn Huệ, Quận 1, TP.HCM');

INSERT INTO USERS (username, password, full_name, email, phone_number, role) VALUES
('admin', 'password123', 'Quản trị viên', 'admin@example.com', '0123456789', 'Admin'),
('manager1', 'manager123', 'Nguyễn Văn A', 'manager1@example.com', '0987654321', 'Quản lý'),
('host1', 'host123', 'Lê Thị B', 'host1@example.com', '0912345678', 'Người cho thuê'),
('tenant1', 'tenant123', 'Trần Văn C', 'tenant1@example.com', '0934567890', 'Người thuê');

INSERT INTO SEARCH_HISTORY (user_id, search_content) VALUES
(1, 'Phòng đơn tại Hà Nội'),
(2, 'Phòng đôi Đà Nẵng'),
(3, 'Phòng gia đình TP.HCM');

 INSERT INTO PACKAGES (package_name, price, duration_days) VALUES
('Gói 3 ngày', 1500000, 3),
('Gói 7 ngày', 3000000, 7),
('Gói 14 ngày', 5000000, 14);

---- code này tam chay dc thoi











